### ISSUE TITLE
npm run start-frontend failed with java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by olegsmetanin** [thelgevold/react-bazel-example#1]
System Version: macOS 10.13.6 (17G65), High Sierra
Kernel Version: Darwin 17.7.0

branch large-app

$ npm run build-frontend
...
INFO: Elapsed time: 944.663s, Critical Path: 29.05s
INFO: 5139 processes: 5139 worker.
INFO: Build completed successfully, 5140 total actions

$ npm run start-frontend
...
Caused by: java.io.IOException: Too many open files
...

Open files limit is increased, https://castorgroup.net/?p=30

$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2048
virtual memory          (kbytes, -v) unlimited

**Comment by thelgevold** [comment]
I just pushed an update. I believe this should be fixed now.

**Comment by olegsmetanin** [comment]
Could you please push changes to the large-app branch to test the fix?

**Comment by thelgevold** [comment]
I think this issue is a limitation of OSX. I have a version in the remote branch that builds the whole thing in Docker (Linux) without running into this issue.
